language: c++
script: /bin/true
env:
 - secure: "TfobwRB2hb3Drsy1wIKPQ1ie+Gjgnb0zUknRr/6X9bMwwOaeIBpOdaUg4Cq0610K2gXBJgChljVoFWhB18aQ7QzoOagKcuWRIALkZdIEI9YDvi2vklREY5ZOii/k1OoSZA5Ll/RSSPIVBVxT0Z2dJCN2FxhUSxhKHJr/Sj4U0GmtBh9HjXvZOmp2z8xxOJ+8kui2EbdWNYjelu4a54HumFG1Zf+A8jT2wJ7nMwl8XnokoREDbTwiseOVHGYLKBaq89xgz/8BWZe8nchUk49Ui0FA9j4dR737xmwSKAFqesJN7CyYgkDwn1hF83RWsd5ntzZrBcNTt9AjPY+Nh5l3lTmbYplkqlbmI9LfZfHMPEEYNx1JcymCLFR2EDn2xWDoG6qkgK2OjbdUEiqXb7OkqomHp4RF3LRiF4pbkObPDUdrD6G3KneGZpHPPwn4Yr3PTB9zdtiv7XkufMmIhlBCUCM2tr5B5Js3+RZasdZ8fDGq/EfY8PMD4aZU2QoiXn+NUlttdJeU1BDjnB5haz7kWbfRjcap97DwvFtH1cbOiLWEl6GZ92oIfuoM9QV7cwqVfeP5Ed+gI26os/rBqfoQ1rwBuKaMCkGhNZ7pu4hqQ9qwxHXILLMO8OGGrz7o7bPHUBQvQ+bItX8nVC3n8Ctkej2I9AZp3soHdE7k4xsvLoE="

before_install:
 - sudo apt-get update
 - sudo apt-get install -y g++ libtclap-dev -qq
 - sudo apt-get install g++-multilib gcc-multilib -qq
install:
 - make && mv fzip fzip-l64 && make clean
 - make "CC=g++ -m32" && mv fzip fzip-l32 && make clean
after_deploy:
 - sudo apt-get install sshpass
 - wget http://www.libsdl.org/projects/SDL_image/docs/demos/lena.png
 - ./fzip-l64 -zc -p lena.png -f lena-out.ifs -s 8 -b 12
 - ./fzip-l64 -x -f lena-out.ifs -p lena-out.png
 - sshpass -p ${PASSWORD} scp lena-out.png remidupre@ssh.alwaysdata.com:/home/remidupre/www/fractal/lena-${TRAVIS_TAG}-${TRAVIS_COMMIT}.png 
 - sshpass -p ${PASSWORD} scp lena-out.ifs remidupre@ssh.alwaysdata.com:/home/remidupre/www/fractal/lena-${TRAVIS_TAG}-${TRAVIS_COMMIT}.ifs 
 
deploy:
  provider: releases
  clean_up: false
  api_key:
    secure: J8NkGxApZPSO+XMUH3gTy/9nBvlf5sLe+FJ+B+3ZiZXEZrpp1YH9v6sBOBb1nKYe3k3hGu+zAvpV6V05gaYNYwyY3fTP0FkCAg/W/k3/MI4iaydBGgd9/iB0H4vNpzH++yZTGKbH7lDd9Jyis5x37iEmKhX4KIH3urtk60puTzULwa+5n3uu5oZExpRWMMMXIe2r7UmIoXw20fw980e016fX7WIBa6IZeAphuUnbV/XPlqIhYd0KQcy2nEux6HxxiZ+c0XCPDCFHh/9aHO8H9hcBvDkaHDSbaZtPG+sTic9IDs8jj4jZchVoFR4yd7pamNTpts5XXuUNt7H8080lc3D9n8HL6ZPk/kbfxNKh+hflFFwN8sqi0/2R0GMauDtGL5LUyDCsoOyplst+/uVh39/BjtneJRqw9Z0vLfHJQb6AUHqUQrGEpiB3DthI/Mgqkv2iO8RPPJ2olN5T79RbWsA/W3pJ5DBK3Kxd/zy8jOkrxMAyR1GehKhC00puvwqRxmRJIGi231c4ec6WAkZV1JWiTYGMyTzqOktiRFHHyI6zqOzWNdwdG7aqj4qMIP4WYPUtAmgIumezE7iGExFsM2duvoa06ac2Y5WvsSpsLokk58SK92QImQA/+RR9cxPEVjiaZxy8piZNL1osYd7FQO9YNpyncAGuEYM1hA8b74s=
  file:
   - fzip-l64
   - fzip-l32
  on:
    tags: true
    repo: remi100756/Compression-Fractale